'use client';
import Link from 'next/link';
import {useState,useEffect,useRef,type ReactNode} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,Bell,Bookmark,CalendarDays,Check,ChevronRight,Clock3,Code2,House,MapPin,Search,Sparkles,Ticket,UserRound,UsersRound,X} from 'lucide-react';
import {sessions,events,filterSessions,type Session} from './data';
const nav=[{id:'home',label:'Home',Icon:House},{id:'program',label:'Program',Icon:CalendarDays},{id:'event',label:'Event',Icon:Sparkles},{id:'mypage',label:'My page',Icon:UserRound}];
function Mark(){return <div className="sdd-mark" role="img" aria-label="SDD"><span className="s-letter"><i/><b/></span><span className="d-letter"><i/><b/></span><span className="d-letter"><i/><b/></span></div>;}
function Cube({className=''}:{className?:string}){return <span aria-hidden="true" className={`cube ${className}`}><i/><b/></span>;}
function Badge({kind}:{kind:string}){return <div aria-hidden="true" className={`object-badge ${kind}`}>{kind==='code'&&<Code2 size={31}/>}<span>{kind.toUpperCase()}</span></div>;}
function SectionTitle({children,href}:{children:ReactNode;href?:string}){return <div className="section-title"><h2>{children}</h2>{href&&<Link href={href}>View all<ArrowUpRight size={15}/></Link>}</div>;}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);return <dialog aria-label={title} ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-heading"><span className="eyebrow">SDD 2026</span><button className="icon-button" onClick={onClose} aria-label="닫기"><X/></button></div><h2>{title}</h2>{children}</dialog>;}
export default function ConferenceApp({page}:{page:string}){
 const [saved,setSaved]=useState<number[]>([]),[interests,setInterests]=useState<string[]>([]),[ready,setReady]=useState(false);
 const [day,setDay]=useState(21),[hall,setHall]=useState('전체'),[search,setSearch]=useState(''),[searchOpen,setSearchOpen]=useState(false);
 const [selected,setSelected]=useState<Session|null>(null),[notice,setNotice]=useState(false),[eventDetail,setEventDetail]=useState<string|null>(null),[myTab,setMyTab]=useState('sessions');
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem('sdd2026-preferences')||'{}');setSaved(Array.isArray(v.sessions)?v.sessions.filter((id:unknown)=>sessions.some(s=>s.id===id)):[]);setInterests(Array.isArray(v.events)?v.events.filter((id:unknown)=>events.some(e=>e.id===id)):[]);}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready){try{localStorage.setItem('sdd2026-preferences',JSON.stringify({sessions:saved,events:interests}));}catch{}}},[saved,interests,ready]);
 const toggleSave=(id:number)=>setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const currentEvent=events.find(e=>e.id===eventDetail),shown=filterSessions(day,hall,search);
 const sessionRow=(s:Session,showDate=false)=><article className="session-row" key={s.id}><div className="session-time">{showDate&&<b>JAN {s.day}</b>}<span>{s.start}</span><span>{s.end}</span></div><span className={`timeline-dot ${s.color}`}/><button className="session-info" onClick={()=>setSelected(s)}><span className="session-type">{s.type}</span><h3>{s.title}</h3><span className="session-location"><MapPin size={12}/>{s.hall}</span></button><button className={`save-button ${saved.includes(s.id)?'saved':''}`} onClick={()=>toggleSave(s.id)} aria-label={`${s.title} ${saved.includes(s.id)?'저장 취소':'저장'}`} aria-pressed={saved.includes(s.id)}><Bookmark size={19}/></button></article>;
 return <div className={`site-shell ${page==='start'?'is-start':''}`}><aside className="desktop-brand"><Link href="/" className="wordmark">SDD <span>2026</span></Link><div className="desktop-message"><span className="eyebrow">S.LSI DEVELOPER DAY</span><h2>Ideas meet.<br/>Possibilities<br/><em>begin.</em></h2><p>같은 호기심으로 연결되어,<br/>함께 만드는 더 밝은 내일.</p><div className="desktop-art"><Cube/><Badge kind="connect"/></div></div><span className="desktop-foot">DEVELOP TOGETHER. BUILD TOMORROW.</span></aside>
 <div className="app-surface">{page==='start'?<main className="start-page"><header className="start-header"><span>SAMSUNG<br/>S.LSI DEVELOPER DAY</span><span>IDEAS<br/>PEOPLE<br/>POSSIBILITIES</span></header><div className="start-top-art"><Badge kind="code"/><Cube className="floating-one"/><span className="dotted-line"/></div><div className="start-main"><Mark/><div className="year">2026<span className="year-dot"/></div><h1>Developers<br/>make a brighter<br/>tomorrow<span>.</span></h1><p>가능성을 연결하고, 내일을 만듭니다.</p></div><div className="start-bottom-art"><Badge kind="build"/><Badge kind="connect"/><Cube className="floating-two"/></div><div className="start-date"><span className="live-dot"/>JAN 21 — 23, 2026 <span className="date-divider"/> COEX, SEOUL</div><Link href="/home" className="primary-button black">Get started<ArrowRight size={22}/></Link><footer className="start-footer"><span>MORE IDEAS. MORE POSSIBILITIES.</span><span>예시 일정 · SDD 2026</span></footer></main>:<>
 <header className="app-header">{page==='home'?<Link href="/home" className="wordmark">SDD <span>2026</span></Link>:<h1>{page==='program'?'Program':page==='event'?'Event':'My page'}</h1>}<button className="icon-button" aria-label={page==='program'?'세션 검색':'공지사항'} onClick={()=>page==='program'?setSearchOpen(v=>!v):setNotice(true)}>{page==='program'?<Search size={24}/>:<><Bell size={23}/><span className="notification-dot"/></>}</button></header>
 <main className={`page-content ${page}`}>
 {page==='home'&&<><section className="home-hero"><span className="eyebrow">S.LSI DEVELOPER DAY</span><h1>More<br/>Developers<br/><span>Together.</span></h1><p>함께 나누는 아이디어,<br/>함께 만드는 더 밝은 내일.</p><Cube/><div className="tiny-manifesto">IDEAS<br/>PEOPLE<br/>TECHNOLOGIES<br/>A BRIGHTER<br/>TOMORROW</div></section><div className="event-date"><CalendarDays size={15}/><span>Jan 21–23, 2026</span><i/><MapPin size={15}/><span>COEX, Seoul</span></div><button className="keynote-card" onClick={()=>setSelected(sessions[0])}><span className="eyebrow">OPENING KEYNOTE</span><h2>A More Open<br/>Galaxy</h2><p>새로운 가능성을 여는 첫 번째 이야기</p><span className="keynote-time">JAN 21 · 09:30 · MAIN STAGE</span><div className="orb"/><Cube/><span className="round-arrow"><ArrowUpRight size={24}/></span></button><div className="quick-links"><Link href="/program"><CalendarDays/><span>Program</span></Link><button onClick={()=>setSelected(sessions[0])}><UsersRound/><span>Speakers</span></button><button onClick={()=>setNotice(true)}><MapPin/><span>Venue</span></button><Link href="/event"><Ticket/><span>Event</span></Link></div><SectionTitle href="/program">Discover what’s next</SectionTitle><Link href="/program" className="featured-card"><div className="mini-pattern"><i/><i/><i/><i/></div><div><span className="eyebrow">THE NEXT CHAPTER</span><h3>Build what’s next.</h3><p>영감을 현실로 만드는 세션</p></div><ChevronRight size={21}/></Link><SectionTitle href="/event">Beyond the sessions</SectionTitle><Link href="/event" className="community-card"><div><span className="eyebrow">MEET. SHARE. CONNECT.</span><h3>새로운 연결의 시작</h3><p>개발자들과 함께하는 특별한 순간</p></div><ArrowUpRight/></Link><p className="sample-note">현재 일정 및 연사 정보는 예시입니다.</p></>}
 {page==='program'&&<><p className="page-intro">아이디어가 시작되는 시간.</p>{searchOpen&&<div className="search-field"><Search size={19}/><input autoFocus aria-label="세션명 또는 연사 검색" placeholder="세션명 또는 연사 검색" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="검색어 지우기" onClick={()=>setSearch('')}><X size={17}/></button>}</div>}<div className="day-selector" aria-label="날짜 선택">{[21,22,23].map((d,i)=><button key={d} className={day===d?'active':''} onClick={()=>setDay(d)} aria-pressed={day===d}><span>JAN</span><b>{d}</b><span>{['WED','THU','FRI'][i]}</span>{day===d&&<i/>}</button>)}</div><div className="hall-tabs" aria-label="강연장 선택">{['전체','Main Stage','Room A','Room B'].map(h=><button key={h} onClick={()=>setHall(h)} className={hall===h?'active':''} aria-pressed={hall===h}>{h}</button>)}</div><div className="schedule-heading"><span>{hall==='전체'?'전체 강연장':hall}<b>{shown.length} sessions</b></span><span><Clock3 size={12}/> KST</span></div><div className="session-list">{shown.map(s=>sessionRow(s))}</div>{shown.length===0&&<div className="empty-state"><Search/><h3>검색된 세션이 없어요</h3><p>다른 검색어 또는 강연장을 선택해주세요.</p><button onClick={()=>{setSearch('');setHall('전체');}}>필터 초기화</button></div>}<p className="sample-note">예시 프로그램 · 실제 행사 일정은 추후 안내됩니다.</p></>}
 {page==='event'&&<><p className="page-intro">세션 너머, 더 많은 가능성.</p><section className="event-hero"><span className="eyebrow">BETTER TOGETHER</span><h2>Same curiosity.<br/><span>New connections.</span></h2><p>배움과 만남이 이어지는 곳,<br/>SDD에서 특별한 경험을 함께하세요.</p><Cube/></section><SectionTitle>Explore & connect <span className="count">03</span></SectionTitle><div className="event-list">{events.map(e=><button key={e.id} className={`event-card ${e.id}`} onClick={()=>setEventDetail(e.id)}><span className="eyebrow">{e.label}</span><h3>{e.title}</h3><p>{e.text}</p><div className="event-card-meta"><Clock3 size={13}/>{e.time}<ArrowUpRight size={18}/></div><div className="event-art"><Badge kind={e.id}/></div>{interests.includes(e.id)&&<span className="interest-badge"><Check size={12}/> 관심 이벤트</span>}</button>)}</div><p className="sample-note">예시 이벤트 · 참여 일정은 추후 확정됩니다.</p></>}
 {page==='mypage'&&<><section className="profile-card"><div className="avatar"><UserRound size={30}/><span/></div><span className="eyebrow">HELLO, DEVELOPER</span><h2>나만의 SDD 2026</h2><p>관심 있는 순간을 한곳에 모아보세요.</p><div className="profile-stats"><button onClick={()=>setMyTab('sessions')}><b>{saved.length.toString().padStart(2,'0')}</b><span>저장한 세션</span></button><i/><button onClick={()=>setMyTab('events')}><b>{interests.length.toString().padStart(2,'0')}</b><span>관심 이벤트</span></button></div><Cube/></section><div className="my-tabs"><button className={myTab==='sessions'?'active':''} onClick={()=>setMyTab('sessions')}>저장한 세션 <span>{saved.length}</span></button><button className={myTab==='events'?'active':''} onClick={()=>setMyTab('events')}>관심 이벤트 <span>{interests.length}</span></button></div>{myTab==='sessions'?(saved.length?<div className="session-list">{sessions.filter(s=>saved.includes(s.id)).sort((a,b)=>a.day-b.day||a.start.localeCompare(b.start)).map(s=>sessionRow(s,true))}</div>:<div className="empty-state"><Bookmark/><h3>어떤 이야기가 궁금하세요?</h3><p>관심 있는 세션의 북마크를 눌러<br/>나만의 프로그램을 만들어보세요.</p><Link href="/program">프로그램 둘러보기 <ArrowRight size={17}/></Link></div>):(interests.length?<div className="saved-events">{events.filter(e=>interests.includes(e.id)).map(e=><button key={e.id} onClick={()=>setEventDetail(e.id)}><Sparkles/><div><h3>{e.title}</h3><p>{e.time} · {e.place}</p></div><ChevronRight/></button>)}</div>:<div className="empty-state"><Sparkles/><h3>새로운 연결을 만나보세요</h3><p>마음에 드는 이벤트를 저장해보세요.</p><Link href="/event">이벤트 둘러보기 <ArrowRight size={17}/></Link></div>)}<div className="local-info"><Check size={15}/><p>저장한 항목은 이 브라우저에 보관됩니다.</p></div><Link href="/" className="back-start"><ArrowLeft size={16}/> 시작 화면으로</Link></>}
 </main><nav className="bottom-nav" aria-label="메인 메뉴">{nav.map(({id,label,Icon})=><Link key={id} href={`/${id}`} className={page===id?'active':''} aria-current={page===id?'page':undefined}><Icon size={23} strokeWidth={1.7}/><span>{label}</span>{page===id&&<i/>}</Link>)}</nav></>}
 </div><aside className="desktop-caption"><span>2026</span><p>MORE DEVELOPERS.<br/>MORE POSSIBILITIES.</p><div className="caption-line"/><span className="vertical-text">SEOUL · JANUARY 21—23</span></aside>
 {selected&&<Modal title={selected.title} onClose={()=>setSelected(null)}><span className="detail-tag">{selected.type}</span><p className="detail-description">{selected.description}</p><div className="detail-meta"><p><CalendarDays size={18}/>2026. 01. {selected.day}</p><p><Clock3 size={18}/>{selected.start}–{selected.end} (KST)</p><p><MapPin size={18}/>{selected.hall}</p></div><div className="speaker"><div className="speaker-avatar"><UserRound/></div><div><b>{selected.speaker}</b><p>{selected.role}</p></div></div><button className="primary-button" onClick={()=>toggleSave(selected.id)}>{saved.includes(selected.id)?'저장한 세션':'세션 저장하기'}{saved.includes(selected.id)?<Check size={20}/>:<Bookmark size={20}/>}</button><p className="sample-note">일정과 연사는 예시 정보입니다.</p></Modal>}
 {notice&&<Modal title="Welcome to SDD 2026" onClose={()=>setNotice(false)}><p className="detail-description">개발자의 아이디어가 더 밝은 내일로 이어지는 곳. S.LSI Developer Day에 오신 것을 환영합니다.</p><div className="detail-meta"><p><CalendarDays size={18}/>2026. 01. 21–23 · 예시 일정</p><p><MapPin size={18}/>COEX, Seoul · 예시 장소</p></div><p className="detail-description">현재 프로그램, 연사, 이벤트는 미리보기를 위한 예시입니다. 실제 일정과 상세 오시는 길은 확정 후 안내됩니다.</p><button className="primary-button" onClick={()=>setNotice(false)}>확인<Check size={20}/></button></Modal>}
 {currentEvent&&<Modal title={currentEvent.title} onClose={()=>setEventDetail(null)}><span className="detail-tag">{currentEvent.label}</span><p className="detail-description">{currentEvent.text}</p><div className="detail-meta"><p><Clock3 size={18}/>{currentEvent.time}</p><p><MapPin size={18}/>{currentEvent.place}</p></div><p className="detail-description">관심 이벤트로 저장하고 My page에서 다시 확인하세요. 참가 신청은 실제 일정 확정 후 안내됩니다.</p><button className="primary-button" onClick={()=>setInterests(v=>v.includes(currentEvent.id)?v.filter(x=>x!==currentEvent.id):[...v,currentEvent.id])}>{interests.includes(currentEvent.id)?'관심 이벤트로 저장됨':'관심 이벤트 저장'}{interests.includes(currentEvent.id)?<Check size={20}/>:<Bookmark size={20}/>}</button><p className="sample-note">저장은 참가 신청이 아닙니다.</p></Modal>}
 </div>;
}
