'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { Check, ChevronLeft, ChevronRight, LogOut, RefreshCw, Search, ShieldCheck, Users, X } from 'lucide-react';
import type { AdminUser, ResetAction } from '../db/admin';
import './style.css';

type Detail={user:AdminUser;attendance:{slot:number;sessionId:number;title:string;room:string;verifiedAt:number}[];audit:{id:string;action:string;reason:string;createdAt:number}[]};
type Listing={users:AdminUser[];total:number;page:number;stats:{users:number;verifications:number;gifts:number;entries:number;maxNumber:number}};
const times=['10:00','11:00','13:30','14:30','15:30'];
const actions:Record<ResetAction,string>={attendance:'수강 인증 전체 초기화',session:'세션 인증 취소',gift:'참여선물 수령 상태 초기화',raffle:'럭키드로우 응모 취소',participation:'전체 참여 기록 초기화'};
const date=(value:number)=>new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
const phone=(value:string)=>`${value.slice(0,3)}-${value.slice(3,7)}-${value.slice(7)}`;
async function api<T>(path:string,body?:unknown):Promise<T>{
 const response=await fetch(`/admin${path}`,{credentials:'same-origin',cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});
 const result=await response.json() as T&{error?:string};
 if(!response.ok){if(response.status===401&&path!=='/api/login')window.dispatchEvent(new Event('admin-expired'));throw new Error(result.error||'요청에 실패했습니다.');}return result;
}
function AdminContent(){
 const [authenticated,setAuthenticated]=useState<boolean|null>(null),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[listing,setListing]=useState<Listing|null>(null),[loading,setLoading]=useState(false);
 const [detail,setDetail]=useState<Detail|null>(null),[detailLoading,setDetailLoading]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null);
 const [reset,setReset]=useState<{action:ResetAction;slot?:number}|null>(null),[reason,setReason]=useState(''),[confirmName,setConfirmName]=useState(''),[success,setSuccess]=useState('');
 useEffect(()=>{let active=true;void api<{authenticated:boolean}>('/api/session').then(r=>{if(active)setAuthenticated(r.authenticated);}).catch(e=>{if(active){setError(e.message);setAuthenticated(false);}});const expired=()=>{setAuthenticated(false);setDetail(null);setListing(null);};window.addEventListener('admin-expired',expired);return()=>{active=false;window.removeEventListener('admin-expired',expired);};},[]);
 useEffect(()=>{if(!authenticated)return;let active=true;async function load(){setLoading(true);try{const r=await api<Listing>(`/api/users?q=${encodeURIComponent(search)}&page=${page}`);if(active){setListing(r);setError('');}}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}}void load();return()=>{active=false;};},[authenticated,search,page,refresh]);
 useEffect(()=>{if(!selectedId||!authenticated)return;let active=true;async function load(){setDetailLoading(true);try{const r=await api<Detail>(`/api/users/${selectedId}`);if(active)setDetail(r);}catch(e){if(active)setError((e as Error).message);}finally{if(active)setDetailLoading(false);}}void load();return()=>{active=false;};},[selectedId,authenticated]);
 async function signIn(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await api('/api/login',{password});setAuthenticated(true);setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function signOut(){setBusy(true);try{await api('/api/logout',{});setAuthenticated(false);setDetail(null);setSelectedId(null);setListing(null);setReset(null);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function applyReset(event:FormEvent){event.preventDefault();if(!detail||!reset||busy)return;setBusy(true);setError('');try{const r=await api<Detail>(`/api/users/${detail.user.id}/reset`,{...reset,reason,confirmName});setDetail(r);setReset(null);setReason('');setConfirmName('');setSuccess('초기화가 완료되었으며 변경 이력이 저장되었습니다.');setRefresh(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function chooseReset(action:ResetAction,slot?:number){setReset({action,slot});setReason('');setConfirmName('');setError('');setSuccess('');}
 if(authenticated===null)return <main className="login-shell"><p>관리자 세션 확인 중…</p></main>;
 if(!authenticated)return <main className="login-shell"><form className="login-card" onSubmit={signIn}><ShieldCheck size={34}/><span className="eyebrow">SDD 2026 · ADMIN</span><h1>행사 운영 관리</h1><p>참가자 인증과 선물 수령, 응모 현황을 관리하세요.</p><label htmlFor="admin-password">관리자 비밀번호</label><input id="admin-password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'로그인 중…':'관리자 로그인'}</button></form></main>;
 return <div className="admin-shell"><header><div><span className="eyebrow">SDD 2026</span><h1>참가자 관리</h1></div><button disabled={busy} onClick={()=>void signOut()}><LogOut size={17}/> 로그아웃</button></header>
 <section className="stats" aria-label="운영 현황">{[['전체 참가자',listing?.stats.users],['수강 인증',listing?.stats.verifications],['선물 수령',listing?.stats.gifts],['유효 응모권',listing?.stats.entries]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value??'–'}</strong></div>)}</section>
 <div className="workspace"><section className="panel users-panel"><div className="panel-heading"><h2><Users size={19}/> 참가자 목록</h2><button aria-label="목록 새로고침" disabled={loading} onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={18}/></button></div><form className="search" onSubmit={e=>{e.preventDefault();setSearch(query.trim());setPage(1);}}><Search size={18}/><input aria-label="이름 또는 전화번호 검색" placeholder="이름 또는 전화번호 검색" value={query} maxLength={80} onChange={e=>setQuery(e.target.value)}/><button type="submit">검색</button></form>
 {error&&<p className="error" role="alert">{error}</p>}
 <div className="table-scroll" aria-busy={loading}><table><thead><tr><th>참가자</th><th>인증</th><th>참여선물</th><th>응모번호</th></tr></thead><tbody>{listing?.users.map(user=><tr key={user.id} className={selectedId===user.id?'selected':''}><td><button className="user-link" disabled={busy} onClick={()=>{setSelectedId(user.id);setDetail(null);setReset(null);setSuccess('');}}><strong>{user.name}</strong><span>{phone(user.phone)}</span></button></td><td>{user.attendanceCount}/5</td><td><span className={user.giftRedeemedAt?'badge green':'badge'}>{user.giftRedeemedAt?'수령 완료':user.giftIssued?'수령 가능':'미대상'}</span></td><td>{user.raffleNumber? <span className={user.raffleVoidedAt?'muted':''}>{user.raffleNumber}번{user.raffleVoidedAt?' · 취소':''}</span>:'–'}</td></tr>)}</tbody></table>{!loading&&listing?.users.length===0&&<p className="empty">검색된 참가자가 없습니다.</p>}</div>
 <div className="pagination"><span>총 {listing?.total??0}명</span><button aria-label="이전 페이지" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><span>{page} / {Math.max(1,Math.ceil((listing?.total??0)/25))}</span><button aria-label="다음 페이지" disabled={loading||page*25>=(listing?.total??0)} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div></section>
 <section className="panel details-panel" aria-label="참가자 상세">{detailLoading?<p className="empty">상세 정보 확인 중…</p>:!detail?<div className="empty"><ShieldCheck size={34}/><h2>참가자를 선택하세요</h2><p>인증 내역과 선물·응모 상태를 확인할 수 있습니다.</p></div>:<>
 <div className="panel-heading"><div><h2>{detail.user.name}</h2><p>{phone(detail.user.phone)}</p></div><button aria-label="상세 닫기" disabled={busy} onClick={()=>{setSelectedId(null);setDetail(null);setReset(null);}}><X size={19}/></button></div>
 {success&&<p className="success" role="status"><Check size={16}/>{success}</p>}
 <h3>수강 인증 <span>{detail.user.attendanceCount}/5</span></h3><ol className="sessions">{times.map((time,i)=>{const record=detail.attendance.find(a=>a.slot===i+1);return <li key={time}><span className={record?'slot verified':'slot'}>{record?<Check size={17}/>:i+1}</span><div><small>{time}{record?` · ${record.room}호`:''}</small><strong>{record?.title||'미인증'}</strong>{record&&<small>{date(record.verifiedAt)} 인증</small>}</div>{record&&<button className="text-danger" disabled={busy} onClick={()=>chooseReset('session',i+1)}>취소</button>}</li>;})}</ol>
 <div className="detail-facts"><div><span>참여선물</span><b>{detail.user.giftRedeemedAt?`수령 완료 · ${date(detail.user.giftRedeemedAt)}`:detail.user.giftIssued?'수령 가능':'미대상'}</b></div><div><span>럭키드로우</span><b>{detail.user.raffleNumber?`${detail.user.raffleNumber}번 · ${detail.user.raffleVoidedAt?'응모 취소':'응모 완료'}`:'미응모'}</b></div></div>
 <div className="reset-actions"><button disabled={busy||!detail.user.attendanceCount} onClick={()=>chooseReset('attendance')}>수강 인증 초기화</button><button disabled={busy||!detail.user.giftRedeemedAt} onClick={()=>chooseReset('gift')}>선물 수령 초기화</button><button disabled={busy||!detail.user.raffleNumber||Boolean(detail.user.raffleVoidedAt)} onClick={()=>chooseReset('raffle')}>응모 취소</button><button className="text-danger" disabled={busy} onClick={()=>chooseReset('participation')}>전체 참여 기록 초기화</button></div>
 {reset&&<form className="reset-confirm" onSubmit={applyReset}><h3>{actions[reset.action]}{reset.slot?` · ${reset.slot}회차`:''}</h3><p>{reset.action==='gift'?'수령 완료 상태를 해제하여 선물을 다시 받을 수 있게 합니다.':reset.action==='raffle'?'추첨 대상에서 제외합니다. 번호는 보존되며 다시 응모하면 복구됩니다.':'인증 취소로 조건을 충족하지 못하면 선물·응모 자격도 해제됩니다. 기존 응모번호는 보존합니다.'}</p><label htmlFor="confirm-name">확인용 참가자 이름</label><input id="confirm-name" value={confirmName} onChange={e=>setConfirmName(e.target.value)} placeholder={detail.user.name} required disabled={busy}/><label htmlFor="reset-reason">초기화 사유</label><textarea id="reset-reason" value={reason} onChange={e=>setReason(e.target.value)} required maxLength={200} disabled={busy}/>{error&&<p className="error" role="alert">{error}</p>}<div><button type="button" disabled={busy} onClick={()=>setReset(null)}>취소</button><button className="danger" disabled={busy||confirmName.trim()!==detail.user.name||!reason.trim()}>{busy?'처리 중…':'확인 후 초기화'}</button></div></form>}
 <h3 className="audit-title">최근 변경 이력</h3><ul className="audit">{detail.audit.map(item=><li key={item.id}><strong>{actions[item.action.split(':')[0] as ResetAction]||item.action}{item.action.includes(':')?` · ${item.action.split(':')[1]}회차`:''}</strong><p>{item.reason}</p><small>{date(item.createdAt)}</small></li>)}</ul>{detail.audit.length===0&&<p className="muted">변경 이력이 없습니다.</p>}
 </>}</section></div><footer>SDD 2026 관리자 · 초기화 내역은 기록됩니다. 마지막 발급 번호: {listing?.stats.maxNumber??'–'}번</footer></div>;
}

export default function AdminApp(){return <div className="admin-app"><AdminContent/></div>;}
