/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=admin/wrangler.jsonc --include-runtime=false --env-interface=AdminEnv admin/env.d.ts` (hash: 5434760911300f786e32945f03e19fed)
interface __BaseEnv_AdminEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	ADMIN_PASSWORD_HASH: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_AdminEnv {}
}
interface AdminEnv extends __BaseEnv_AdminEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_PASSWORD_HASH">> {}
}
